### ISSUE TITLE
Unable to find a specification for `ComScore`

### ISSUE THREAD

**Issue by RicoGeoibour** [comScore/ComScore-iOS-watchOS-tvOS#2]
Getting this error while trying to add Comscore dependancy to my project with cocoapods. Any help ?

**Comment by raspu** [comment]
When are you getting this error? While building or while adding the pod? Can you share your Podfile with us?

**Comment by RicoGeoibour** [comment]
pod file looks like:
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
...
#Comscore
pod 'ComScore'
end

**Comment by raspu** [comment]
When are you getting this error?

**Comment by RicoGeoibour** [comment]
when doing pod install

**Comment by RicoGeoibour** [comment]
Ok solved by adding path to the repo:
    pod 'ComScore', :git => 'https://github.com/comscore/ComScore-iOS-watchOS-tvOS'
thx

**Comment by raspu** [comment]
That shouldn't be needed... Let us know if this happens again.

**Comment by RicoGeoibour** [comment]
Ok
Where can I get the latest implementation guid ?

**Comment by joezeitouny** [comment]
You can contact your comScore representative to obtain the relevant implementation guide.

**Comment by raspu** [comment]
Would you be so kind of running `pod update --verbose` with the Podfile as before and then copying the output? To see what the issue was?

**Comment by RicoGeoibour** [comment]
Resolving dependencies of `Podfile`
[!] Unable to find a specification for `ComScore`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/resolver.rb:442:in `handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/resolver.rb:65:in `rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/resolver.rb:57:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:693:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:691:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/update.rb:60:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
