### ISSUE TITLE
Improve Example implementation

### ISSUE THREAD

**Issue by Remyoman** [comScore/ComScore-iOS-watchOS-tvOS#3]
The Example project doesn't include any code that uses any analytics events. It would be nice to see these added to the example. 

Besides that I wasn't able to find any clear documentation for migrating from version 3 to version 5.

**Comment by joezeitouny** [comment]
For the time being we're only providing a basic Hello World example that contains the bare minimum code statements to tag with our library as specified by our implementation instructions.

As for your second remark. Can you ask your comScore representative to provide you with the relevant documentation.

**Comment by joezeitouny** [comment]
I'm closing this issue for now
