### ISSUE TITLE
StreamSense

### ISSUE THREAD

**Issue by davidgeijer** [comScore/ComScore-iOS-watchOS-tvOS#4]
Hi 

Is stream sense included in this package ?

If yes, how do i implement tracking of my streams as in http://www.cmf-fmc.ca/documents/files/programs/dm-reporting/comscore/Stream-Sense-for-iOS.pdf

Seams that there are allot of headers that is re-named or deleted.

Best Regards David

**Comment by joezeitouny** [comment]
The documentation you are referring to is not hosted by comScore and is over 4 years old. Our Streaming Tag product has changed over time and you require updated documentation. Please contact your comScore client services representative to get updated documentation that is appropriate for your implementation needs. I'm closing this issue for now.

**Comment by joezeitouny** [comment]
We asked around, if you weren't able to figure out your contact representative at comScore yet you can send an email to tagsupport@comscore.com mentioning in your client name, client ID and a description of the project that you're working on so that we can help you further on tagging with us.
